.github/ISSUE_TEMPLATE/1_main_issue.yml, .github/ISSUE_TEMPLATE/2_be_issue.yml, .github/ISSUE_TEMPLATE/3_fe_issue.yml, frontend/.cta.json, frontend/index.html, frontend/package.json, frontend/public/manifest.json, frontend/src/routes/__root.tsx, frontend/src/routes/customer/escort/$escortId/completed/index.tsx, frontend/src/routes/customer/escort/$escortId/helper/$helperId/index.tsx, frontend/src/routes/customer/escort/$escortId/index.tsx, frontend/src/routes/customer/escort/$escortId/payment/index.tsx, frontend/src/routes/customer/escort/$escortId/review/$reviewStep/index.tsx, frontend/src/routes/customer/index.tsx, frontend/src/routes/customer/recruit/$recruitStep/index.tsx, frontend/src/routes/dashboard/$escortId/customer/index.tsx, frontend/src/routes/dashboard/$escortId/helper/index.tsx, frontend/src/routes/dashboard/$escortId/map/index.tsx, frontend/src/routes/helper/application/$escortId/index.tsx, frontend/src/routes/helper/application/completed/index.tsx, frontend/src/routes/helper/application/index.tsx, frontend/src/routes/helper/escort/$escortId/index.tsx, frontend/src/routes/helper/escort/$escortId/report/$reportStep/index.tsx, frontend/src/routes/helper/index.tsx, frontend/src/routes/helper/profile/index.tsx, frontend/src/routes/helper/profile/new/$newStep/index.tsx, frontend/src/routes/login/index.tsx, frontend/tsconfig.json
- Closes #17 
---
---
1. 페이지 라우팅 만들었습니다.
URL 논의한대로 같이 routes 폴더 생성했습니다. (tanstack router 파일 기반 라우팅입니다)
2. 폴더구조 정의
현재 저희 라우팅을 보시면 크게, customer, dashboard, helper, login(auth)로 나뉘어져서
이 분류에 맞춰서 기능(도메인)기반 폴더구조로 결정했습니다.
현재 정해진 폴더구조는 다음과 같습니다.
```
frontend
├── 📁 dist/
├── 📁 node_modules/
├── 📁 public/
├── 📁 src/
│   ├── 📁 assets/
│   ├── 📁 features/
│   │   ├── 📁 auth/
│   │   │   ├── 📁 apis/
│   │   │   ├── 📁 components/
│   │   │   ├── 📁 hooks/
│   │   │   ├── 📁 types/
│   │   │   └── 📁 utils/
│   │   ├── 📁 customer/
│   │   ├── 📁 dashboard/
│   │   └── 📁 helper/
│   │
│   ├── 📁 routes/
│   │   ├── 📁 customer/
│   │   ├── 📁 dashboard/
│   │   ├── 📁 helper/
│   │   ├── 📁 login/
│   │   ├── __root.tsx
│   │   └── index.tsx
│   │
│   ├── 📁 shared/
│   │   ├── 📁 apis/ …
```
=> [FE] Common > 폴더 구조 정의 #17

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/routes/components/index.tsx, frontend/src/shared/components/Button.tsx, frontend/src/shared/components/index.ts, frontend/src/styles.css
- Closes #22 
---
---
1. 내용1
- `button` 컴포넌트 추가 및 `router/components`페이지 추가
```ts
interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
disabled?: boolean;
variant?: 'primary' | 'secondary' | 'assistive';
size?: 'sm' | 'md' | 'lg';
isLoading?: boolean;
}
```
---
=> [FE] COMMON > 버튼 컴포넌트 추가

backend/server/src/main/java/com/todoc/server/common/util/JsonUtil.java, backend/server/src/test/java/com/todoc/server/common/util/JsonUtilTest.java
- Closes #27 
---
---
---
**1. JSON 직렬화/역직렬화 유틸 클래스(`JsonUtil`) 추가**
- Java 객체 → JSON 문자열 변환 메서드 `toJson()` 구현
- JSON 문자열 → Java 객체 역직렬화 메서드 `fromJson()` 2종류 구현
- `Class<T>` 타입
- `TypeReference<T>` 제네릭 타입
<br>
**2. `JsonUtil` 유틸 클래스 테스트 코드 추가**
- 객체 → JSON 문자열 직렬화 테스트
- List → JSON 문자열 직렬화 테스트
- JSON 문자열 → `Class<T>` 타입 역직렬화 테스트
- JSON 문자열 → `TypeReference<T>` 제네릭 타입 역직렬화 테스트
---
-
- JUnit 테스트로 직렬화/역직렬화 결과 이상 없는지 확인했습니다.
- 추가적으로 필요한 유틸 기능 있으면 피드백 주세요!
- 테스트 수행 결과입니다.
=> [BE] Common > Util 공통 클래스 작성 #27

backend/server/src/main/java/com/todoc/server/common/response/Response.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/RecruitCreateRequest.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitListResponse.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java
- Closes #52 
---
---
---
1. '동행 신청하기 화면'에서 발생하는 요청인 `동행 신청하기` API에 해당하는 `Controller`, `Request`를 작성했습니다.
---
-
- 컨트롤러 함수가 1개 밖에 없네요.. ㅎㅎ 너무 잘게 쪼갠건 아닐지.. ㅎㅎ
- `동행 신청하기` api에서 사용되는 dto 필드를 wiki에 추가했습니다.
=> [BE] [SUB] Customer > 동행 신청하기 Controller 및 DTO 작성 #52

backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/RecruitCreateRequest.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java, backend/server/src/main/resources/application-local.yml, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
- Closes #51 
---
---
---
1. 홈화면에서 고객(customer)가 동행 신청 목록을 조회하는 로직인 getRecruitListAsCustomerByUserId() 함수에 대한 테스트 코드를 작성했습니다.
---
-
- 나머지 코드는 이전 리뷰에서 피드백 받았으므로, Test 파일만 확인해주시면 됩니다!
-  현재 service 코드에서는 예외처리를 할 요소가 없어서 예외 상황 테스트를 진행하지 않았습니다.
=> [BE] [SUB] Customer > 동행 목록 조회 테스트코드 작성 #51

backend/server/src/main/java/com/todoc/server/domain/customer/web/dto/response/PatientSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/RecruitCreateRequest.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitDetailResponse.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperListResponse.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/report/web/controller/ReportController.java, backend/server/src/main/java/com/todoc/server/domain/report/web/dto/response/ReportDetailResponse.java, backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/LocationInfoSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteSimpleResponse.java, backend/server/src/main/resources/application-local.yml
- Closes #56 
---
---
---
1. RecruitController
- 특정 동행 신청에 대한 상세 정보 조회
- 동행 신청 취소
2. HelperController
- 특정 동행 신청에 지원한 도우미 목록 조회
3. ReportController
- 특정 리포트에 대한 상세 정보 조회
---
-
- DTO 필드 네이밍 컨벤션 문서 갱신했습니다.
=> [BE] [SUB] Customer > 동행 내역 상세페이지 Controller 및 DTO 작성 #56

backend/server/src/main/java/com/todoc/server/domain/auth/entity/Auth.java, backend/server/src/main/java/com/todoc/server/domain/customer/entity/Patient.java, backend/server/src/main/java/com/todoc/server/domain/customer/repository/PatientRepository.java, backend/server/src/main/java/com/todoc/server/domain/customer/service/PatientService.java, backend/server/src/main/java/com/todoc/server/domain/escort/entity/Recruit.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitFacadeService.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/request/RecruitCreateRequest.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/route/entity/LocationInfo.java, backend/server/src/main/java/com/todoc/server/domain/route/entity/Route.java, backend/server/src/main/java/com/todoc/server/domain/route/repository/LocationInfoRepository.java, backend/server/src/main/java/com/todoc/server/domain/route/repository/RouteRepository.java, backend/server/src/main/java/com/todoc/server/domain/route/service/LocationInfoService.java, backend/server/src/main/java/com/todoc/server/domain/route/service/RouteService.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitFacadeServiceTest.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
- Closes #53 
- Closes #54 
---
---
---
1. 동행 신청 과정에서 요청으로 받은 `RecruitCreateRequest`로부터 `Recruit`, `Patient`, `Route`, `LocationInfo` 엔티티를 생성하는 `CreateRecruit()`를 작성했습니다.
- 다만, 경로 API를 적용하지 않았기에, `Route`, `LocationInfo`는 기본 생성자로 만들었습니다. TODO를 표기했습니다.
2. `RecruitCreateRequest`의 필드 타입이 잘못되었거나, 필드명이 컨벤션에 어긋난 부분을 수정했습니다.
3. 동행 목록 조회 API의 URL을 변경했습니다.
4. `CreateRecruit()` 에 대한 테스트 코드를 작성했습니다.
---
-
- Facade 코드에 대한 의문점이나 피드백을 남겨주시면 감사하겠습니다.
- DTO 클래스의 필드명이나, 타입, Controller 메서드 URL 수정내역에 대해서 확인해주세요!
=> [BE] [SUB] Customer > 동행 신청하기 Service 및 DAO 계층, 테스트코드 #53

backend/server/src/main/java/com/todoc/server/common/util/DateTimeUtils.java, backend/server/src/main/java/com/todoc/server/common/util/JsonUtils.java, backend/server/src/main/java/com/todoc/server/domain/auth/exception/AuthErrorCode.java, backend/server/src/main/java/com/todoc/server/domain/auth/exception/AuthException.java, backend/server/src/main/java/com/todoc/server/domain/auth/exception/AuthNotFoundException.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java, backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperErrorCode.java, backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperNotFoundException.java, backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperResponseCode.java, backend/server/src/main/java/com/todoc/server/domain/helper/repository/CertificateJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/helper/repository/HelperJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/CertificateService.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperFacadeService.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperDetailResponse.java, backend/server/src/main/java/com/todoc/server/domain/review/repository/PositiveFeedbackChoiceQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/review/repository/ReviewQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/review/service/PositiveFeedbackChoiceService.java, backend/server/src/main/java/com/todoc/server/domain/review/service/ReviewService.java, backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java, backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/PositiveFeedbackStatResponse.java, backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/ReviewStatResponse.java, backend/server/src/test/java/com/todoc/server/common/exception/ExceptionTestController.java, backend/server/src/test/java/com/todoc/server/common/util/JsonUtilsTest.java, backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperFacadeServiceTest.java
- Closes #60
- Closes #61 
---
---
---
1. 도우미 상세 정보 조회 기능 구현
- HelperFacadeService를 통해 도우미의 모든 정보를 통합 조회
- 내부적으로 도우미 정보, 나이 계산, 동행 횟수, 리뷰 통계, 후기 키워드, 자격증, 강점 목록 등을 조합
2. 리뷰 관련 기능 추가
- ReviewQueryRepository를 통해 리뷰 통계 및 최신 5건 조회 로직 구현
- PositiveFeedbackChoiceQueryRepository를 통해 후기 키워드 통계 조회 로직 구현
3. 도우미 자격증 조회 기능 구현
- CertificateJpaRepository에서 helperId 기준으로 자격증 type 목록 조회
4. 기타
- Json 파싱 유틸(JsonUtils) 활용해 강점(strength) 필드 파싱
- 생년월일을 통해 나이를 계산하는 유틸 클래스(DateTimeUtils) 추가
5. HelperFacadeService에 대한 테스트 코드 작성
- userId에 해당하는 도우미가 존재하는 경우
- userId에 해당하는 도우미가 존재하지 않는 경우
---
-
- H2에 더미데이터 저장해두고 수동 테스트까지 완료했습니다!
=> [BE] Customer > 도우미 상세 Service 및 DAO 계층 로직 작성 #60

backend/server/src/main/java/com/todoc/server/common/config/SwaggerConfig.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java, backend/server/src/main/java/com/todoc/server/domain/report/web/controller/ReportController.java, backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java
- Closes #112 
---
---
---
1. 프론트엔드 팀원분들의 의견을 반영하여 Schema가 전체적으로 반영되도록 수정했습니다.
- 컨트롤러의 `@ApiResponse`에 포함된 `@Schema(implementation = RecruitSimpleResponse.class)` 명시를 제거했습니다.
2. 원격 서버의 Swagger UI에서 실행할 경우 CORS 에러가 발생하는 문제를 해결했습니다.
- swagger url을 `"/"` 를 default 경로로 지정했습니다.
---
-
- Key Changes에 적혀있는 내용이 전부입니다!
=> [BE] [SUB] Setting > Swagger 세팅 오류 수정 #112

backend/server/src/main/java/com/todoc/server/common/entity/BaseEntity.java, backend/server/src/main/java/com/todoc/server/domain/auth/entity/Auth.java, backend/server/src/main/java/com/todoc/server/domain/customer/entity/Patient.java, backend/server/src/main/java/com/todoc/server/domain/escort/entity/Application.java, backend/server/src/main/java/com/todoc/server/domain/escort/entity/Escort.java, backend/server/src/main/java/com/todoc/server/domain/escort/entity/Recruit.java, backend/server/src/main/java/com/todoc/server/domain/helper/entity/Certificate.java, backend/server/src/main/java/com/todoc/server/domain/helper/entity/Helper.java, backend/server/src/main/java/com/todoc/server/domain/lastlocation/entity/LatestLocation.java, backend/server/src/main/java/com/todoc/server/domain/latestlocation/entity/LatestLocation.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/ImageAttachment.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/Report.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/TaxiFee.java, backend/server/src/main/java/com/todoc/server/domain/review/entity/PositiveFeedback.java, backend/server/src/main/java/com/todoc/server/domain/review/entity/PositiveFeedbackChoice.java, backend/server/src/main/java/com/todoc/server/domain/review/entity/Review.java, backend/server/src/main/java/com/todoc/server/domain/route/entity/LocationInfo.java, backend/server/src/main/java/com/todoc/server/domain/route/entity/Route.java
- Closes #120 
---
---
---
1. 모든 Entity에 `@SQLRestriction` 추가 했습니다.
2. BaseEntity의 `deprecated`된 `@Where`과 `@SQLDelete`를 제거했습니다.
3. 패키지명 lastlocation -> latestlocation으로 변경했습니다.
---
Hibernate Deprecated 목록에 @Where @SQLDelete가 존재합니다.
https://docs.jboss.org/hibernate/orm/6.3/javadocs/deprecated-list.html?utm_source=chatgpt.com
- soft delete 해야할 것을 그냥 delete 하는 코드는 아직 없더라구요~!
그래서 엔티티만 수정했습니다!
- soft delete 는 앞으로도 명시적으로 신경써서 해야할 것 같습니다.
=> [BE] [SUB] Setting > Deprecated 기능에 대한 soft delete 코드 수정 #120

backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java, backend/server/src/main/java/com/todoc/server/domain/review/web/dto/request/ReviewCreateRequest.java
- Closes #86 
---
---
---
1. 리뷰 작성을 위한 Controller 함수 및 DTO 클래스를 작성했습니다.
- `ReviewCreateRequest` DTO 클래스
- `ReviewController.createReview()` 함수
2. 기존 RecruitController의 description에 오타가 있어 수정했습니다.
---
-
-`ReviewCreateRequest`에서 `positiveFeedbackList`을 List 형태로 받고, 저장할 때 json으로 파싱하는거 맞을까요 ?
=> [BE] [SUB] Customer > 동행 리뷰 작성하기 Controller 및 DTO 작성 #86

backend/server/src/main/java/com/todoc/server/common/enumeration/ApplicationStatus.java, backend/server/src/main/java/com/todoc/server/domain/escort/entity/Application.java
- Closes #129
---
---
---
1. Application 엔티티에 Status 필드 추가
2. ApplicationStatus 클래스에서 Enum 정의
- PENDING("대기중")
- MATCHED("매칭성공")
- FAILED("매칭실패")
---
-
-
=> [BE] [SUB] Customer > 동행 지원 상태값 추가 #129

backend/server/src/main/java/com/todoc/server/common/enumeration/ApplicationStatus.java, backend/server/src/main/java/com/todoc/server/common/enumeration/Area.java, backend/server/src/main/java/com/todoc/server/common/enumeration/EscortStatus.java, backend/server/src/main/java/com/todoc/server/common/enumeration/Gender.java, backend/server/src/main/java/com/todoc/server/common/enumeration/RecruitStatus.java, backend/server/src/main/java/com/todoc/server/domain/customer/exception/CustomerErrorCode.java, backend/server/src/main/java/com/todoc/server/domain/customer/exception/PatientGenderInvalidException.java, backend/server/src/main/java/com/todoc/server/domain/customer/service/PatientService.java, backend/server/src/main/java/com/todoc/server/domain/customer/web/dto/response/PatientSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/RecruitController.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperSimpleResponse.java, backend/server/src/main/java/com/todoc/server/domain/review/exception/ReviewErrorCode.java, backend/server/src/main/java/com/todoc/server/domain/review/web/controller/ReviewController.java, backend/server/src/main/java/com/todoc/server/domain/review/web/dto/response/ReviewSimpleResponse.java, backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperFacadeServiceTest.java
- Closes #133
---
---
---
1. Request, Response에서 Enum값이 아닌, String으로 변환된 값을 관리하도록 수정했습니다.
- 그에 따른 Service, Controller, Test 코드를 함께 수정했습니다.
2. Enum 클래스마다 `String` -> `Optional<Enum>` 으로 변경하는 from() 함수를 작성했습니다.
- String에 대응하는 Enum이 존재하지 않을 경우 `orElseThrow()` 로 예외처리를 할 수 있도록 했습니다.
3. Enum 필드가 존재하지 않는 상황에 대한 `ErrorCode` 및 `Exception`을 생성했습니다.
---
-
- `Errorcode` `Exception`을 확인해주시면 감사하겠습니다.
- 또한, `from()`함수를 어떻게 사용했는지 확인해주시면 감사하겠습니다 ( 704376ed2ffe2f696596eb2098e944d8c6617b44 PatientService.java )
=> [BE] [SUB] Customer > Request, Response의 Enum 필드 수정 #133

backend/server/src/main/java/com/todoc/server/common/config/WebConfig.java
- Closes #136 
---
---
---
1. localhost:3000에 대해 cors 에러가 발생하지 않도록 수정했습니다.
---
-
-
=> [BE] [SUB] Setting > CORS 에러 해결 #136

backend/server/src/main/java/com/todoc/server/domain/escort/service/ApplicationFacadeService.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/controller/ApplicationController.java, backend/server/src/main/java/com/todoc/server/domain/helper/repository/HelperJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperFacadeService.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/controller/HelperController.java, backend/server/src/main/java/com/todoc/server/domain/helper/web/dto/response/HelperSimpleResponse.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/ApplicationFacadeServiceTest.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitFacadeServiceTest.java, backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperFacadeServiceTest.java, backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperServiceTest.java
- Closes #132 
---
---
---
1. HelperSimpleResponse에서 authId 필드 제거
- 객체 생성하는 부분들에 변경 사항 반영하여 수정
2. Helper 도메인에서 도우미 상세 정보를 조회할 때, helperProfileId 기준으로 검색
- 메서드명, 매개변수명에 명시적으로 표현
---
-
- 기존 테스트 코드와 수동 테스트에 이상 없이 동작하는지 확인했습니다!
=> [BE] [SUB] Customer > DTO에서 authId 제거 #132

backend/server/src/main/java/com/todoc/server/common/dto/request/ImageCreateRequest.java, backend/server/src/main/java/com/todoc/server/common/entity/ImageMeta.java, backend/server/src/main/java/com/todoc/server/common/entity/ImageObject.java, backend/server/src/main/java/com/todoc/server/domain/escort/entity/Escort.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/ApplicationQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/ApplicationService.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/ImageAttachment.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/Report.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/TaxiFee.java, backend/server/src/main/java/com/todoc/server/domain/report/entity/TaxiReceiptImage.java, backend/server/src/main/java/com/todoc/server/domain/report/repository/ImageAttachmentJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/report/repository/TaxiReceiptImageJpaRepository.java, backend/server/src/main/java/com/todoc/server/domain/report/service/ImageAttachmentService.java, backend/server/src/main/java/com/todoc/server/domain/report/service/ReportFacadeService.java, backend/server/src/main/java/com/todoc/server/domain/report/service/ReportService.java, backend/server/src/main/java/com/todoc/server/domain/report/service/TaxiFeeService.java, backend/server/src/main/java/com/todoc/server/domain/report/service/TaxiReceiptImageService.java, backend/server/src/main/java/com/todoc/server/domain/report/web/controller/ReportController.java, backend/server/src/main/java/com/todoc/server/domain/report/web/dto/request/ReportCreateRequest.java, backend/server/src/main/java/com/todoc/server/domain/report/web/dto/response/ReportDefaultValueResponse.java, backend/server/src/test/resources/sql/data.sql
- Closes #96
---
---
---
1. 리포트 작성 관련 API Controller 및 DTO
2. 이미지 관련 엔티티를 S3 확장성을 고려하여 수정
- ImageObject 추상 클래스를 구현하도록
3. Escort에 실제 만남/도착 시간 필드 추가
---
-
-
=> [BE] [SUB] Helper > 리포트 작성 Controller 작성 #96

backend/server/src/main/java/com/todoc/server/common/config/WebConfig.java, backend/server/src/main/java/com/todoc/server/domain/auth/web/AuthInterceptor.java
=> [Chore] CORS에 대한 수정

backend/server/src/main/java/com/todoc/server/common/config/SwaggerConfig.java
- Closes #1
---
---
---
1. Swagger에서 Cookie를 통한 인증 구현
---
-
-
=> [BE] [SUB] Setting > Swagger에서 Cookie를 통한 인증 #196

backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitFacadeService.java, backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapAPICallException.java, backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapErrorCode.java, backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapInternalException.java, backend/server/src/main/java/com/todoc/server/external/tmap/exception/TMapParsingException.java, backend/server/src/main/java/com/todoc/server/external/tmap/service/TMapRouteParser.java, backend/server/src/main/java/com/todoc/server/external/tmap/service/TMapRouteService.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitFacadeServiceTest.java
- Closes #222 
---
---
---
1. `TMapAPIException`, `TMapParsingException` 으로 분리했습니다.
---
-
-
=> [BE] [SUB] Route > 외부 TMAP API 호출에 대한 예외 구체화 #222

backend/server/src/main/java/com/todoc/server/ServerApplication.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/EscortService.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitScheduler.java
- Closes #1
---
---
---
1. 동행시간 3시간 전인 동행에 대해 status를 변경하는 스케쥴러 코드를 작성했습니다.
- 1분마다 스케쥴러 코드가 동작합니다.
---
-
-
=> [BE] [SUB] Escort > 각 동행별 3시간 전 동행 상태를 변경하는 스케줄링 코드 작성 #228

backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java, backend/server/src/main/java/com/todoc/server/domain/escort/web/dto/response/RecruitPaymentResponse.java, backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteDetailResponse.java, backend/server/src/main/java/com/todoc/server/domain/route/web/dto/response/RouteSimpleResponse.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
- Closes #244
---
---
---
`RouteSimpleRepsonse`에는 위치정보만, `RouteDetailResponse`에는 경로정보까지 들어가야 하는데, 
`RouteSimpleRepsonse`에 경로정보가 담겨져있던 문제를 수정했습니다.
`RouteDetailResponse`의 이동 시간 필드에 대한 description을 `분->초` 로 변경했습니다.
---
-
사전에 이야기 나눈대로, 리뷰 없이 머지하겠습니다.
=> [BE] [SUB] Route > Route 경로가 필요하지 않은 곳에도 경로를 제공하던 API 문제 해결 #244

.github/workflows/backend-pr-ci.yml, backend/server/build.gradle.kts, backend/server/src/main/java/com/todoc/server/common/config/RedisConfig.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/EscortQueryRepository.java, backend/server/src/main/resources/application-ci.yml, backend/server/src/main/resources/application-local.yml, backend/server/src/main/resources/application-prod.yml, backend/server/src/main/resources/application.yml
- Closes #239 
---
---
---
CRUDRepository 대신, 범용성이 높은 RedisTemplate을 쓰는게 어떨까 싶습니다.
**1. Redis 사용을 위한 라이브러리를 불러왔습니다.**
**2. 설정파일(.yml)에 설정 값을 추가했습니다.**
- application.yml
```
spring
data:
redis:
repositories:
enabled: false // CRUDRepository를 사용하지 않겠다고 명시하여, 스프링 경고 문구 출력을 제거
timeout: 3s
```
- application-local.yml
```
spring:
data:
redis:
host: localhost
port: 6379
```
- application-prod.yml
```
spring:
data:
redis:
host: ${REDIS_HOST}
port: 6379
```
**3. RedisConfig 클래스를 작성했습니다.**
- String, Value에 대한 JSON 직렬화 지정
- Hash 구조에 대해서도 JSON 직렬화를 지정했습니다.
---
-
-
=> [BE] [SUB] Setting > Redis 설정 클래스 추가 #239

.github/workflows/backend-pr-ci.yml, backend/server/src/main/java/com/todoc/server/common/config/RedisConfig.java, backend/server/src/main/java/com/todoc/server/domain/latestlocation/repository/LocationCacheRepository.java, backend/server/src/main/java/com/todoc/server/domain/latestlocation/service/LocationService.java, backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/controllerv2/LocationController.java, backend/server/src/main/java/com/todoc/server/domain/latestlocation/web/dto/request/LocationRequest.java, backend/server/src/main/resources/application-ci.yml, backend/server/src/test/java/com/todoc/server/IntegrationTestBase.java, backend/server/src/test/java/com/todoc/server/ServerApplicationTests.java, backend/server/src/test/java/com/todoc/server/domain/auth/service/AuthIntegrationTest.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/ApplicationIntegrationTest.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/EscortIntegrationTest.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitIntegrationTest.java, backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperIntegrationTest.java, backend/server/src/test/java/com/todoc/server/domain/report/service/ReportIntegrationTest.java, backend/server/src/test/java/com/todoc/server/domain/review/service/ReviewIntegrationTest.java
- Closes #241
---
---
---
1. 위치정보를 캐시에 저장하는 `LocationCacheRepository`를 생성했습니다.
2. 위치정보를 클라이언트로부터 입력받기 위해 `LocationService` `LocationController`를 생성했습니다.
---
-
-
**컨트롤러 호출 후 Redis 상태입니다.**
=> [BE] [SUB] Dashboard > 도우미가 서버로 보내는 마지막 위치정보 수신 기능 구현 #241

backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperErrorCode.java, backend/server/src/main/java/com/todoc/server/domain/helper/exception/HelperProfileAlreadyCreatedException.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperFacadeService.java, backend/server/src/main/java/com/todoc/server/domain/helper/service/HelperService.java, backend/server/src/main/java/com/todoc/server/domain/route/Coordinate.java, backend/server/src/main/java/com/todoc/server/external/tmap/service/TMapRouteParser.java, backend/server/src/test/java/com/todoc/server/domain/helper/service/HelperIntegrationTest.java
- Closes #274
---
---
---
1. 경로 경위도 관련 오류 수정
- 필드 NotNull 처리
- 경위도 값 서로 바뀌어 저장되는 문제 해결
2. 환자 프로필이 이미 있는 경우 새로 생성할 수 없도록 제한
---
-
-
=> [BE] [SUB] Helper > 환자 프로필이 이미 있는 경우 새로 생성할 수 없도록 제한 #274

backend/server/build.gradle.kts, backend/server/src/main/java/com/todoc/server/common/config/S3Config.java
- Closes #285
---
---
---
1. S3 sdk-core 버젼 충돌 해결
---
-
-
=> [BE] [SUB] Images > S3 접속 오류 해결 #285

backend/server/src/main/java/com/todoc/server/common/config/WebConfig.java, backend/server/src/main/java/com/todoc/server/domain/escort/repository/RecruitQueryRepository.java, backend/server/src/main/java/com/todoc/server/domain/escort/service/RecruitService.java, backend/server/src/test/java/com/todoc/server/domain/escort/service/RecruitServiceTest.java
- Closes #326 
---
---
---
1. HOTFIX로 빠르게 배포합니다.
---
-
-
=> [BE] [SUB] QA > 1차 QA 수정사항 반영 (2) #326

backend/server/src/main/java/com/todoc/server/domain/realtime/repository/LocationCacheRepository.java, backend/server/src/main/java/com/todoc/server/domain/realtime/repository/RedisLocationScriptsConfig.java
- Closes #347 
---
---
---
1. 위치 변화 없어도 30초에 한 번은 새로운 위치 정보 전송하도록 수정
---
-
-
=>  [BE] [SUB] Dashboard > 위치 변화 없어도 30초에 한 번은 새로운 위치 정보 전송하도록 수정 #347

backend/server/src/main/java/com/todoc/server/domain/realtime/repository/LocationCacheRepository.java, backend/server/src/main/java/com/todoc/server/domain/realtime/repository/RedisLocationScriptsConfig.java, backend/server/src/main/java/com/todoc/server/domain/realtime/service/RealtimeFacadeService.java
- Closes #353 
---
---
---
1. 레디스에 문자열 "null"이 저장되는 문제 해결
---
-
-
=> [BE] [SUB] Dashboard > 레디스에 문자열 "null"이 저장되는 문제 해결 #353
